### ISSUE TITLE
アップロードされた画像のサムネイルの方向が正しくない

### ISSUE THREAD

**Issue by otofune** [misskey-delta/misskey-file#8]
https://github.com/misskey-delta/misskey-web/issues/160

**Comment by otofune** [comment]
graphicsmagickだろうか？

**Comment by rokoucha** [comment]
Exifのorientationタグを読まないといけないらしい
http://qiita.com/minodisk/items/b7bab1b3f351f72d534b

**Comment by otofune** [comment]
そういえばなおったんでしたっけ。
